#!/usr/bin/env node
// Regenerates the vendored qunitx browser runtime + stylesheet that qunitx-cli embeds, so
// consumer projects can run tests without installing the separate `qunitx` runtime package.
// The esbuild runtime plugin (lib/setup/qunitx-runtime-plugin.ts) hands qunitx-runtime.js to the
// consumer's build as an in-memory virtual module when `qunitx` isn't resolvable; qunit.css is
// served by the web server. Run `make vendor` after bumping the qunitx devDependency and commit
// the outputs — they are pinned to whatever qunitx version is installed here.
import esbuild from 'esbuild';
import { createRequire } from 'node:module';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(repoRoot, 'package.json'));
// qunitx's exports map doesn't expose ./package.json, so resolve the entry and derive the
// package root from the path (same regex the old resolveQunitxRoot used).
const qunitxEntry = require.resolve('qunitx');
const rootMatch = /^(.*[\\/]qunitx)[\\/]/.exec(qunitxEntry);
if (!rootMatch) throw new Error(`Could not derive qunitx root from ${qunitxEntry}`);
const qunitxRoot = rootMatch[1];
const version = JSON.parse(await readFile(join(qunitxRoot, 'package.json'), 'utf8')).version;

const vendorDir = join(repoRoot, 'templates/vendor');
await mkdir(vendorDir, { recursive: true });

// Bundle qunitx's browser entry (default export = QUnit, named `module`/`test`/`assert`/…) into
// one self-contained ESM file with vendor/qunit.js inlined, so it has no remaining imports the
// consumer's native esbuild sidecar would need to resolve from disk. platform:'browser' selects
// the `default` (browser) export condition rather than node/deno.
const result = await esbuild.build({
  stdin: {
    contents: `export * from 'qunitx';\nexport { default } from 'qunitx';\n`,
    resolveDir: repoRoot,
  },
  bundle: true,
  format: 'esm',
  platform: 'browser',
  legalComments: 'none',
  sourcemap: false,
  write: false,
  banner: {
    js: `// GENERATED by scripts/write-vendor-runtime.ts from qunitx@${version} — do not edit; run \`make vendor\`.`,
  },
});

await writeFile(join(vendorDir, 'qunitx-runtime.js'), result.outputFiles[0].text);
await copyFile(join(qunitxRoot, 'vendor/qunit.css'), join(vendorDir, 'qunit.css'));
await writeFile(join(vendorDir, '.qunitx-version'), `${version}\n`);

console.log(`templates/vendor/qunitx-runtime.js written (qunitx@${version})`);
console.log('templates/vendor/qunit.css written');
